### ISSUE TITLE
[bug] generate_registers.py generates an invalid `uhal` address table for the BLASTER RAM

### ISSUE THREAD

**Issue by jsturdy** [evka85/GEM_AMC#24]
The `uhal` generated address table has a typo:
```xml
<node id="GBT" address="0x0" permission="rw" mode="block"size="3312"/>
```
which should be (space between the `"` closing the `mode` and the next key `size`):
```xml
<node id="GBT" address="0x0" permission="rw" mode="block" size="3312"/>
```

**Comment by jsturdy** [comment]
@evka85, as mentioned in person, the problem is here:
https://github.com/evka85/GEM_AMC/blob/4fe3966902053eed9ceea75b8c95ccb8db07076c/scripts/generate_registers.py#L634-L641

where there are no leading/trailing spaces for `mask`/`mode`/`size`

**Comment by jsturdy** [comment]
@evka85 this needs to be fixed before the next FW release

**Comment by evka85** [comment]
fixed in v3.8.4

**Comment by jsturdy** [comment]
Not fixed... see cms-gem-daq-project/cmsgemos#292 (or incorrect address tables attached to release)
