### ISSUE TITLE
[bug] UHAL address tables generated incorrectly

### ISSUE THREAD

**Issue by jsturdy** [evka85/GEM_AMC#37]
The current (3.8.3) address tables for `uhal` introduce syntax errors (in addition to those introduced in #24):
`uhal._core.exception: Bit-masked nodes are not allowed to have child nodes`
In the following, `MGT_CHANNEL_63.RESET` can not have a mask because it has child nodes (and many other places in this new block `OPTICAL_LINKS`)
```xml
      <node id="MGT_CHANNEL_63" address="0xfc0" >
        <node id="RESET" address="0x1" permission="rw" mask="0x3">
          <node id="TX_RESET" address="0x0" permission="rw" mask="0x1"/>
          <node id="RX_RESET" address="0x0" permission="rw" mask="0x2"/>
        </node>
        <node id="CTRL" address="0x2" permission="rw" mask="0x7f">
          <node id="TX_POWERDOWN" address="0x0" permission="rw" mask="0x1"/>
          <node id="RX_POWERDOWN" address="0x0" permission="rw" mask="0x2"/>
          <node id="TX_POLARITY" address="0x0" permission="rw" mask="0x4"/>
          <node id="RX_POLARITY" address="0x0" permission="rw" mask="0x8"/>
          <node id="LOOPBACK" address="0x0" permission="rw" mask="0x10"/>
          <node id="TX_INHIBIT" address="0x0" permission="rw" mask="0x20"/>
          <node id="RX_LOW_POWER_MODE" address="0x0" permission="rw" mask="0x40"/>
          <node id="RX_PRBS_SEL" address="0x1" permission="rw" mask="0x7"/>
          <node id="TX_PRBS_SEL" address="0x1" permission="rw" mask="0x70"/>
          <node id="PRBS_CNT_RESET" address="0x2" permission="w" mask="0x1"/>
          <node id="RX_ERROR_CNT_RESET" address="0x3" permission="w" mask="0x1"/>
        </node>
        <node id="STATUS" address="0x0" permission="r" mask="0xf">
          <node id="TX_RESET_DONE" address="0x0" permission="r" mask="0x1"/>
          <node id="RX_RESET_DONE" address="0x0" permission="r" mask="0x2"/>
          <node id="CPLL_LOCKED" address="0x0" permission="r" mask="0x4"/>
          <node id="CPLL_REF_CLK_LOST" address="0x0" permission="r" mask="0x8"/>
          <node id="PRBS_ERROR_CNT" address="0x4" permission="r" />
          <node id="PRBS_ERROR_CNT" address="0x4" permission="r" />
          <node id="RX_NOT_IN_TABLE_CNT" address="0x5" permission="r" />
          <node id="RX_DISPERR_CNT" address="0x6" permission="r" />
        </node>
      </node>
    </node>
```

**Comment by jsturdy** [comment]
@evka85 this needs to be fixed before the next FW release

**Comment by evka85** [comment]
fixed in v3.8.4

**Comment by jsturdy** [comment]
Not fixed... (or incorrect address table attached to release)
```xml
      <node id="MGT_CHANNEL_0" address="0x0" >
        <node id="RESET" address="0x1" permission="rw" mask="0x3">
          <node id="TX_RESET" address="0x0" permission="rw" mask="0x1"/>
          <node id="RX_RESET" address="0x0" permission="rw" mask="0x2"/>
        </node>
        <node id="CTRL" address="0x2" permission="rw" mask="0x7f">
          <node id="TX_POWERDOWN" address="0x0" permission="rw" mask="0x1"/>
```
